# Generated by Django 3.2.6 on 2021-10-08 14:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0002_auto_20211008_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=100, null=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
